apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: aruba-api-mock-claim0
  name: aruba-api-mock-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
